#数据库
spring:
        datasource:
                url: jdbc:mysql://localhost:3306/test
                username: root
                password: root
                driver-class-name: com.mysql.jdbc.Driver
        jpa:
              show-sql: true
              database: mysql

#tomcat
server:
      port: 8888

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.test.demo.po
logging:
  level:
    com.test.demo.mapper:debug





